jobs:
  - name: gke-man
    type: manifest
    steps:
      - GET: gke-sn
      - GET: image-opts
      - GET: trigger-gke-man

  - name: gke-beta-deploy
    type: gkeDeploy
    options:
      deployMethod: upgrade
    steps:
      - GET: gke-man
      - GET: gke-cluster
